apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: kerooehab/ticket-backend:5
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: DATABASE_HOST
              value: "postgres"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: ticketing
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
